In [1]:
!pip install spacy

Requirement already satisfied: spacy in c:\users\kiit\anaconda31\lib\site-packages (3.7.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (0.12.3)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (4.65.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (1.10.12)
Requirement already satisfied: jinja2 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (3.1.3)
Requirement already satisfied: setuptools in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (68.2.2)
Requirement already satisfied: packaging>=20.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: language-data>=1.2 in c:\users\kiit\anaconda31\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.2.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\kiit\anaconda31\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\kiit\anaconda31\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiit\anaconda31\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiit\anaconda31\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiit\anaconda31\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.2.2)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\users\kiit\anaconda31\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\kiit\anaconda31\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\kiit\anaconda31\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\kiit\anaconda31\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\kiit\anaconda31\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\kiit\anaconda31\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (13.3.5)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\kiit\anaconda31\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.18.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\kiit\anaconda31\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\kiit\anaconda31\lib\site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: marisa-trie>=0.7.7 in c:\users\kiit\anaconda31\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.0)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\kiit\anaconda31\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\kiit\anaconda31\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\kiit\anaconda31\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)

In [2]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     --------------------------------------- 0.0/12.8 MB 245.8 kB/s eta 0:00:52
     --------------------------------------- 0.1/12.8 MB 381.3 kB/s eta 0:00:34
     --------------------------------------- 0.1/12.8 MB 504.4 kB/s eta 0:00:26
      -------------------------------------- 0.2/12.8 MB 827.9 kB/s eta 0:00:16
     - -------------------------------------- 0.3/12.8 MB 1.0 MB/s eta 0:00:12
     - -------------------------------------- 0.4/12.8 MB 1.1 MB/s eta 0:00:12
     - -------------------------------------- 0.6/12.8 MB 1.4 MB/s eta 0:00:09
     -- ------------------------------------- 0.7/12.8 MB 1.4 MB/s eta 0:00:09
     -- ------------------------------------- 0.7/12.8 MB 1.4 MB/s eta 0:00:09
     -- ------------------------------------- 0.9/12.8 MB 1.5 MB/s eta 0:00:08
     --- ------------------------------------ 1.0/12.8 MB 1.6 MB/s eta 0:00:08
     --- ------------------------------------ 1.2/12.8 MB 1.7 MB/s eta 0:00:07
     ---- ----------------------------------- 1.3/12.8 MB 1.8 MB/s eta 0:00:07
     ---- ----------------------------------- 1.5/12.8 MB 1.9 MB/s eta 0:00:06
     ---- ----------------------------------- 1.5/12.8 MB 2.0 MB/s eta 0:00:06
     ----- ---------------------------------- 1.6/12.8 MB 1.9 MB/s eta 0:00:06
     ----- ---------------------------------- 1.6/12.8 MB 1.9 MB/s eta 0:00:06
     ----- ---------------------------------- 1.8/12.8 MB 1.9 MB/s eta 0:00:06
     ----- ---------------------------------- 1.8/12.8 MB 1.9 MB/s eta 0:00:06
     ------ --------------------------------- 1.9/12.8 MB 1.9 MB/s eta 0:00:06
     ------ --------------------------------- 2.0/12.8 MB 1.9 MB/s eta 0:00:06
     ------ --------------------------------- 2.1/12.8 MB 1.9 MB/s eta 0:00:06
     ------ --------------------------------- 2.2/12.8 MB 1.9 MB/s eta 0:00:06
     ------ --------------------------------- 2.2/12.8 MB 1.9 MB/s eta 0:00:06
     ------- -------------------------------- 2.3/12.8 MB 1.8 MB/s eta 0:00:06
     ------- -------------------------------- 2.3/12.8 MB 1.8 MB/s eta 0:00:07
     ------- -------------------------------- 2.3/12.8 MB 1.7 MB/s eta 0:00:07
     ------- -------------------------------- 2.4/12.8 MB 1.7 MB/s eta 0:00:07
     ------- -------------------------------- 2.5/12.8 MB 1.7 MB/s eta 0:00:06
     -------- ------------------------------- 2.7/12.8 MB 1.8 MB/s eta 0:00:06
     -------- ------------------------------- 2.7/12.8 MB 1.8 MB/s eta 0:00:06
     -------- ------------------------------- 2.8/12.8 MB 1.7 MB/s eta 0:00:06
     -------- ------------------------------- 2.8/12.8 MB 1.7 MB/s eta 0:00:06
     -------- ------------------------------- 2.9/12.8 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 3.0/12.8 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 3.1/12.8 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 3.1/12.8 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 3.1/12.8 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 3.1/12.8 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 3.1/12.8 MB 1.6 MB/s eta 0:00:07
     --------- ------------------------------ 3.2/12.8 MB 1.6 MB/s eta 0:00:07
     --------- ------------------------------ 3.2/12.8 MB 1.6 MB/s eta 0:00:07
     ---------- ----------------------------- 3.2/12.8 MB 1.5 MB/s eta 0:00:07
     ---------- ----------------------------- 3.2/12.8 MB 1.5 MB/s eta 0:00:07
     ---------- ----------------------------- 3.2/12.8 MB 1.5 MB/s eta 0:00:07
     ---------- ----------------------------- 3.3/12.8 MB 1.5 MB/s eta 0:00:07
     ---------- ----------------------------- 3.3/12.8 MB 1.5 MB/s eta 0:00:07
     ---------- ----------------------------- 3.4/12.8 MB 1.5 MB/s eta 0:00:07
     ---------- ----------------------------- 3.4/12.8 MB 1.4 MB/s eta 0:00:07
     ---------- ----------------------------- 3.5/12.8 MB 1.4 MB/s eta 0:00:07
     ----------- ---------------------------- 3.6/12.8 MB 1.4 MB/s eta 0:00:07
     ----------- ---------------------------- 3.7/12.8 MB 1.4 MB/s eta 0:00:07
     ----------- ---------------------------- 3.8/12.8 MB 1.5 MB/s eta 0:00:07
     ------------ --------------------------- 3.9/12.8 MB 1.5 MB/s eta 0:00:07
     ------------ --------------------------- 3.9/12.8 MB 1.5 MB/s eta 0:00:07
     ------------ --------------------------- 4.0/12.8 MB 1.5 MB/s eta 0:00:07
     ------------ --------------------------- 4.1/12.8 MB 1.5 MB/s eta 0:00:06
     ------------ --------------------------- 4.2/12.8 MB 1.5 MB/s eta 0:00:06
     ------------- -------------------------- 4.2/12.8 MB 1.5 MB/s eta 0:00:06
     ------------- -------------------------- 4.3/12.8 MB 1.5 MB/s eta 0:00:06
     ------------- -------------------------- 4.4/12.8 MB 1.5 MB/s eta 0:00:06
     ------------- -------------------------- 4.4/12.8 MB 1.5 MB/s eta 0:00:06
     -------------- ------------------------- 4.5/12.8 MB 1.5 MB/s eta 0:00:06
     -------------- ------------------------- 4.5/12.8 MB 1.5 MB/s eta 0:00:06
     -------------- ------------------------- 4.6/12.8 MB 1.5 MB/s eta 0:00:06
     -------------- ------------------------- 4.7/12.8 MB 1.5 MB/s eta 0:00:06
     --------------- ------------------------ 4.8/12.8 MB 1.5 MB/s eta 0:00:06
     --------------- ------------------------ 4.9/12.8 MB 1.5 MB/s eta 0:00:06
     --------------- ------------------------ 5.0/12.8 MB 1.5 MB/s eta 0:00:06
     --------------- ------------------------ 5.1/12.8 MB 1.5 MB/s eta 0:00:06
     --------------- ------------------------ 5.1/12.8 MB 1.5 MB/s eta 0:00:06
     ---------------- ----------------------- 5.2/12.8 MB 1.5 MB/s eta 0:00:06
     ---------------- ----------------------- 5.2/12.8 MB 1.5 MB/s eta 0:00:06
     ---------------- ----------------------- 5.3/12.8 MB 1.5 MB/s eta 0:00:06
     ---------------- ----------------------- 5.4/12.8 MB 1.5 MB/s eta 0:00:05
     ----------------- ---------------------- 5.6/12.8 MB 1.5 MB/s eta 0:00:05
     ----------------- ---------------------- 5.6/12.8 MB 1.5 MB/s eta 0:00:05
     ----------------- ---------------------- 5.7/12.8 MB 1.5 MB/s eta 0:00:05
     ----------------- ---------------------- 5.7/12.8 MB 1.5 MB/s eta 0:00:05
     ------------------ --------------------- 5.8/12.8 MB 1.5 MB/s eta 0:00:05
     ------------------ --------------------- 5.9/12.8 MB 1.5 MB/s eta 0:00:05
     ------------------ --------------------- 6.0/12.8 MB 1.5 MB/s eta 0:00:05
     ------------------- -------------------- 6.1/12.8 MB 1.5 MB/s eta 0:00:05
     ------------------- -------------------- 6.2/12.8 MB 1.5 MB/s eta 0:00:05
     ------------------- -------------------- 6.2/12.8 MB 1.5 MB/s eta 0:00:05
     ------------------- -------------------- 6.3/12.8 MB 1.5 MB/s eta 0:00:05
     ------------------- -------------------- 6.3/12.8 MB 1.5 MB/s eta 0:00:05
     ------------------- -------------------- 6.4/12.8 MB 1.5 MB/s eta 0:00:05
     ------------------- -------------------- 6.4/12.8 MB 1.5 MB/s eta 0:00:05
     -------------------- ------------------- 6.5/12.8 MB 1.5 MB/s eta 0:00:05
     -------------------- ------------------- 6.5/12.8 MB 1.5 MB/s eta 0:00:05
     -------------------- ------------------- 6.6/12.8 MB 1.5 MB/s eta 0:00:05
     -------------------- ------------------- 6.6/12.8 MB 1.5 MB/s eta 0:00:05
     -------------------- ------------------- 6.7/12.8 MB 1.5 MB/s eta 0:00:05
     --------------------- ------------------ 6.8/12.8 MB 1.5 MB/s eta 0:00:05
     --------------------- ------------------ 6.9/12.8 MB 1.5 MB/s eta 0:00:04
     --------------------- ------------------ 7.0/12.8 MB 1.5 MB/s eta 0:00:04
     ---------------------- ----------------- 7.1/12.8 MB 1.5 MB/s eta 0:00:04
     ---------------------- ----------------- 7.1/12.8 MB 1.5 MB/s eta 0:00:04
     ---------------------- ----------------- 7.2/12.8 MB 1.5 MB/s eta 0:00:04
     ---------------------- ----------------- 7.2/12.8 MB 1.5 MB/s eta 0:00:04
     ---------------------- ----------------- 7.3/12.8 MB 1.5 MB/s eta 0:00:04
     ----------------------- ---------------- 7.4/12.8 MB 1.5 MB/s eta 0:00:04
     ----------------------- ---------------- 7.5/12.8 MB 1.5 MB/s eta 0:00:04
     ----------------------- ---------------- 7.6/12.8 MB 1.5 MB/s eta 0:00:04
     ----------------------- ---------------- 7.7/12.8 MB 1.5 MB/s eta 0:00:04
     ------------------------ --------------- 7.8/12.8 MB 1.5 MB/s eta 0:00:04
     ------------------------ --------------- 7.9/12.8 MB 1.5 MB/s eta 0:00:04
     ------------------------ --------------- 7.9/12.8 MB 1.5 MB/s eta 0:00:04
     ------------------------ --------------- 8.0/12.8 MB 1.5 MB/s eta 0:00:04
     ------------------------- -------------- 8.1/12.8 MB 1.5 MB/s eta 0:00:04
     ------------------------- -------------- 8.2/12.8 MB 1.5 MB/s eta 0:00:04
     ------------------------- -------------- 8.2/12.8 MB 1.5 MB/s eta 0:00:04
     ------------------------- -------------- 8.3/12.8 MB 1.5 MB/s eta 0:00:03
     -------------------------- ------------- 8.4/12.8 MB 1.5 MB/s eta 0:00:03
     -------------------------- ------------- 8.5/12.8 MB 1.5 MB/s eta 0:00:03
     -------------------------- ------------- 8.6/12.8 MB 1.5 MB/s eta 0:00:03
     --------------------------- ------------ 8.6/12.8 MB 1.5 MB/s eta 0:00:03
     --------------------------- ------------ 8.8/12.8 MB 1.5 MB/s eta 0:00:03
     --------------------------- ------------ 8.9/12.8 MB 1.5 MB/s eta 0:00:03
     ---------------------------- ----------- 9.0/12.8 MB 1.5 MB/s eta 0:00:03
     ---------------------------- ----------- 9.1/12.8 MB 1.6 MB/s eta 0:00:03
     ---------------------------- ----------- 9.2/12.8 MB 1.6 MB/s eta 0:00:03
     ----------------------------- ---------- 9.3/12.8 MB 1.6 MB/s eta 0:00:03
     ----------------------------- ---------- 9.3/12.8 MB 1.6 MB/s eta 0:00:03
     ----------------------------- ---------- 9.4/12.8 MB 1.6 MB/s eta 0:00:03
     ----------------------------- ---------- 9.4/12.8 MB 1.6 MB/s eta 0:00:03
     ----------------------------- ---------- 9.5/12.8 MB 1.6 MB/s eta 0:00:03
     ------------------------------ --------- 9.6/12.8 MB 1.6 MB/s eta 0:00:03
     ------------------------------ --------- 9.7/12.8 MB 1.6 MB/s eta 0:00:02
     ------------------------------ --------- 9.8/12.8 MB 1.6 MB/s eta 0:00:02
     ------------------------------ --------- 9.8/12.8 MB 1.6 MB/s eta 0:00:02
     ------------------------------- -------- 9.9/12.8 MB 1.6 MB/s eta 0:00:02
     ------------------------------- -------- 10.0/12.8 MB 1.6 MB/s eta 0:00:02
     ------------------------------- -------- 10.1/12.8 MB 1.6 MB/s eta 0:00:02
     ------------------------------- -------- 10.2/12.8 MB 1.6 MB/s eta 0:00:02
     -------------------------------- ------- 10.3/12.8 MB 1.6 MB/s eta 0:00:02
     -------------------------------- ------- 10.4/12.8 MB 1.6 MB/s eta 0:00:02
     -------------------------------- ------- 10.5/12.8 MB 1.6 MB/s eta 0:00:02
     -------------------------------- ------- 10.6/12.8 MB 1.6 MB/s eta 0:00:02
     --------------------------------- ------ 10.6/12.8 MB 1.6 MB/s eta 0:00:02
     --------------------------------- ------ 10.6/12.8 MB 1.6 MB/s eta 0:00:02
     --------------------------------- ------ 10.8/12.8 MB 1.6 MB/s eta 0:00:02
     ---------------------------------- ----- 10.9/12.8 MB 1.6 MB/s eta 0:00:02
     ---------------------------------- ----- 11.0/12.8 MB 1.6 MB/s eta 0:00:02
     ---------------------------------- ----- 11.1/12.8 MB 1.6 MB/s eta 0:00:02
     ---------------------------------- ----- 11.1/12.8 MB 1.6 MB/s eta 0:00:02
     ---------------------------------- ----- 11.1/12.8 MB 1.6 MB/s eta 0:00:02
     ----------------------------------- ---- 11.2/12.8 MB 1.6 MB/s eta 0:00:02
     ----------------------------------- ---- 11.3/12.8 MB 1.6 MB/s eta 0:00:01
     ----------------------------------- ---- 11.3/12.8 MB 1.6 MB/s eta 0:00:01
     ----------------------------------- ---- 11.4/12.8 MB 1.6 MB/s eta 0:00:01
     ----------------------------------- ---- 11.5/12.8 MB 1.5 MB/s eta 0:00:01
     ------------------------------------ --- 11.6/12.8 MB 1.5 MB/s eta 0:00:01
     ------------------------------------ --- 11.7/12.8 MB 1.5 MB/s eta 0:00:01
     ------------------------------------ --- 11.7/12.8 MB 1.5 MB/s eta 0:00:01
     ------------------------------------ --- 11.8/12.8 MB 1.5 MB/s eta 0:00:01
     ------------------------------------- -- 11.9/12.8 MB 1.5 MB/s eta 0:00:01
     ------------------------------------- -- 11.9/12.8 MB 1.5 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 1.5 MB/s eta 0:00:01
     -------------------------------------- - 12.2/12.8 MB 1.5 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 1.5 MB/s eta 0:00:01
     -------------------------------------- - 12.4/12.8 MB 1.5 MB/s eta 0:00:01
     -------------------------------------- - 12.4/12.8 MB 1.6 MB/s eta 0:00:01
     -------------------------------------- - 12.5/12.8 MB 1.5 MB/s eta 0:00:01
     ---------------------------------------  12.5/12.8 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------  12.7/12.8 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------  12.8/12.8 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------  12.8/12.8 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 1.5 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in c:\users\kiit\anaconda31\lib\site-packages (from en-core-web-sm==3.7.1) (3.7.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.12.3)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (4.65.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.10.12)
Requirement already satisfied: jinja2 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.1.3)
Requirement already satisfied: setuptools in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (68.2.2)
Requirement already satisfied: packaging>=20.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in c:\users\kiit\anaconda31\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in c:\users\kiit\anaconda31\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.2.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\kiit\anaconda31\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (4.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\kiit\anaconda31\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kiit\anaconda31\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kiit\anaconda31\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kiit\anaconda31\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2024.2.2)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\users\kiit\anaconda31\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\kiit\anaconda31\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.1.5)
Requirement already satisfied: colorama in c:\users\kiit\anaconda31\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\kiit\anaconda31\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\kiit\anaconda31\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\kiit\anaconda31\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (13.3.5)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\kiit\anaconda31\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.18.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\kiit\anaconda31\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\kiit\anaconda31\lib\site-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.1.3)
Requirement already satisfied: marisa-trie>=0.7.7 in c:\users\kiit\anaconda31\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.2.0)

In [2]:
import spacy

In [3]:
nlp = spacy.load("en_core_web_sm")

In [7]:
with open ("emlopyeedetails.txt", "r") as f:
    text = f.read()

In [8]:
print(text)

     ID_NO FIRST_NAME                                         LAST_NAME                                                 AGE     SALARY
---------- -------------------------------------------------- -------------------------------------------------- ---------- ----------
       101 Anata                                              Sarkar                                                     28      55000
       102 Asutosh                                            Mukherjee                                                  34      63000
       103 Rada                                               Sengupto                                                   25      45000
       104 Bulai                                              Chandra                                                    45      80000
       105 Chaitali                                           Mukherjee                                                  30      57000

In [9]:
doc = nlp(text)

In [10]:
print (doc)

     ID_NO FIRST_NAME                                         LAST_NAME                                                 AGE     SALARY
---------- -------------------------------------------------- -------------------------------------------------- ---------- ----------
       101 Anata                                              Sarkar                                                     28      55000
       102 Asutosh                                            Mukherjee                                                  34      63000
       103 Rada                                               Sengupto                                                   25      45000
       104 Bulai                                              Chandra                                                    45      80000
       105 Chaitali                                           Mukherjee                                                  30      57000

In [11]:
print (len(text))
print (len(doc))

946
61

In [17]:
for token in text[0:10]:
    print (token)

I
D
_
N

In [18]:
for token in doc[:10]:
    print (token)

ID_NO
FIRST_NAME

LAST_NAME

AGE

SALARY

In [19]:
for token in text.split()[:10]:
    print (token)

ID_NO
FIRST_NAME
LAST_NAME
AGE
SALARY
----------
--------------------------------------------------
--------------------------------------------------
----------
----------

In [20]:
for sent in doc.sents:
    print (sent)

     ID_NO FIRST_NAME                                         LAST_NAME                                                 AGE     SALARY
----------
--------------------------------------------------
--------------------------------------------------
----------
----------
       101 Anata                                              Sarkar                                                     28      55000
       102 Asutosh                                            Mukherjee                                                  34      63000
       103 Rada                                               Sengupto                                                   25      45000
       104 Bulai                                              Chandra                                                    45      80000
       105 Chaitali                                           Mukherjee                                                  30      57000

In [22]:
sentence1 = list(doc.sents)[0]
print (sentence1)

     ID_NO FIRST_NAME                                         LAST_NAME                                                 AGE     SALARY
----------

In [4]:
import spacy

# Load the spaCy model
nlp = spacy.load("en_core_web_sm")

# Sample sentence
sentence = "Find employees aged above 30 with the highest salary."

# Function to convert a sentence to SQL command using POS tagging
def sentence_to_sql_with_pos(sentence):
    doc = nlp(sentence)

    # Initialize variables for constructing the SQL query
    table_name = "Employees"
    select_clause = "SELECT *"
    where_clause = ""
    order_by_clause = ""
    limit_clause = "FETCH FIRST 1 ROWS ONLY"

    # Flags to track if age and salary conditions are found
    age_condition_found = False
    salary_condition_found = False

    # Extract components based on POS tagging
    for token in doc:
        if token.pos_ == "NOUN" and token.text.lower() == "employees":
            continue  # Skip reference to table name
        if token.pos_ == "VERB" and token.text.lower() == "find":
            continue  # Skip verbs not relevant to SQL construction
        if token.pos_ == "ADJ" and token.head.pos_ == "NOUN":
            if token.head.text.lower() == "age" and token.text.lower() in ("above", "greater", "more"):
                next_token = doc[token.i + 1]
                where_clause += f"age > {next_token.text} "
                age_condition_found = True
            elif token.head.text.lower() == "salary" and token.text.lower() == "highest":
                order_by_clause = "ORDER BY salary DESC "
                salary_condition_found = True

    # If age condition is not found, default to age > 30
    if not age_condition_found:
        where_clause = "WHERE age > 30 "

    # Construct the final SQL query
    sql_query = f"{select_clause} FROM {table_name} "
    if where_clause:
        sql_query += where_clause
    if order_by_clause:
        sql_query += order_by_clause
    sql_query += limit_clause

    return sql_query.strip()

# Convert the sentence to SQL command using POS tagging
sql_command = sentence_to_sql_with_pos(sentence)
print("Generated SQL command:")
print(sql_command)

Generated SQL command:
SELECT * FROM Employees WHERE age > 30 ORDER BY salary DESC FETCH FIRST 1 ROWS ONLY

In [5]:
import spacy
import pandas as pd

nlp = spacy.load("en_core_web_sm")

#datasets
data = {
    "id_no": [101, 102, 103, 104, 105],
    "first_name": ["Anata", "Asutosh", "Rada", "Bulai", "Chaitali"],
    "last_name": ["Sarkar", "Mukherjee", "Sengupto", "Chandra", "Mukherjee"],
    "age": [28, 34, 25, 45, 30],
    "salary": [55000.00, 63000.00, 45000.00, 80000.00, 57000.00]
}

df = pd.DataFrame(data)

# Function to convert a sentence to SQL command using POS tagging
def sentence_to_sql_with_pos(sentence):
    doc = nlp(sentence)

    # Initialize variables for constructing the SQL query
    table_name = "Employees"
    select_clause = "SELECT *"
    where_clause = ""
    order_by_clause = ""
    limit_clause = ""

    # Flags to track if age and salary conditions are found
    age_condition_found = False
    salary_condition_found = False

    # Extract components based on POS tagging
    for token in doc:
        if token.pos_ == "NOUN" and token.text.lower() == "employees":
            continue 
        if token.pos_ == "VERB" and token.text.lower() in ("find", "show", "list", "get"):
            continue 
        if token.pos_ == "ADJ" and token.head.pos_ == "NOUN":
            if token.head.text.lower() == "age" and token.text.lower() in ("above", "greater", "more", "older"):
                next_token = doc[token.i + 1]
                where_clause += f"age > {next_token.text} "
                age_condition_found = True
            elif token.head.text.lower() == "salary" and token.text.lower() == "highest":
                order_by_clause = "ORDER BY salary DESC "
                limit_clause = "FETCH FIRST 1 ROWS ONLY"
                salary_condition_found = True
            elif token.head.text.lower() == "salary" and token.text.lower() == "lowest":
                order_by_clause = "ORDER BY salary ASC "
                limit_clause = "FETCH FIRST 1 ROWS ONLY"
                salary_condition_found = True

    # Construct the final SQL query
    sql_query = f"{select_clause} FROM {table_name} "
    if where_clause:
        sql_query += "WHERE " + where_clause
    if order_by_clause:
        sql_query += order_by_clause
    if limit_clause:
        sql_query += limit_clause

    return sql_query.strip()

# Sample sentences
sentences = [
    "Find employees aged above 30 with the highest salary.",
    "Show me the employees who are older than 25.",
    "List the employees with the lowest salary.",
    "Get the details of employees with a salary above 50000."
]

def execute_sql(df, sql_query):
    # This is a simplistic SQL executor for pandas DataFrame
    # It supports only SELECT * and simple WHERE clauses for this example
    if "WHERE" in sql_query:
        query = sql_query.split("WHERE")[1].strip().split(" ")[0] + " " + sql_query.split("WHERE")[1].strip().split(" ")[1] + " " + sql_query.split("WHERE")[1].strip().split(" ")[2]
        result = df.query(query)
    else:
        result = df

    if "ORDER BY" in sql_query:
        order_by_clause = sql_query.split("ORDER BY")[1].strip().split()[0]
        ascending = "ASC" in sql_query
        result = result.sort_values(by=order_by_clause, ascending=ascending)

    if "FETCH FIRST" in sql_query:
        limit = int(sql_query.split("FETCH FIRST")[1].strip().split()[0])
        result = result.head(limit)

    return result

# Execute the generated SQL commands
for sentence in sentences:
    sql_command = sentence_to_sql_with_pos(sentence)
    print("Generated SQL command:")
    print(sql_command)
    result = execute_sql(df, sql_command)
    print("Result:")
    print(result)
    print("\n")

Generated SQL command:
SELECT * FROM Employees ORDER BY salary DESC FETCH FIRST 1 ROWS ONLY
Result:
   id_no first_name last_name  age   salary
3    104      Bulai   Chandra   45  80000.0


Generated SQL command:
SELECT * FROM Employees
Result:
   id_no first_name  last_name  age   salary
0    101      Anata     Sarkar   28  55000.0
1    102    Asutosh  Mukherjee   34  63000.0
2    103       Rada   Sengupto   25  45000.0
3    104      Bulai    Chandra   45  80000.0
4    105   Chaitali  Mukherjee   30  57000.0


Generated SQL command:
SELECT * FROM Employees ORDER BY salary ASC FETCH FIRST 1 ROWS ONLY
Result:
   id_no first_name last_name  age   salary
2    103       Rada  Sengupto   25  45000.0


Generated SQL command:
SELECT * FROM Employees
Result:
   id_no first_name  last_name  age   salary
0    101      Anata     Sarkar   28  55000.0
1    102    Asutosh  Mukherjee   34  63000.0
2    103       Rada   Sengupto   25  45000.0
3    104      Bulai    Chandra   45  80000.0
4    105   Chaitali  Mukherjee   30  57000.0

In [5]:
import spacy
import pandas as pd

nlp = spacy.load("en_core_web_sm")

#datasets
data = {
    "id_no": [101, 102, 103, 104, 105],
    "first_name": ["Anata", "Asutosh", "Rada", "Bulai", "Chaitali"],
    "last_name": ["Sarkar", "Mukherjee", "Sengupto", "Chandra", "Mukherjee"],
    "age": [28, 34, 25, 45, 30],
    "salary": [55000.00, 63000.00, 45000.00, 80000.00, 57000.00]
}

df = pd.DataFrame(data)

# Function to convert a sentence to SQL command using POS tagging
def sentence_to_sql_with_pos(sentence):
    doc = nlp(sentence)

    # Initialize variables for constructing the SQL query
    table_name = "Employees"
    select_clause = "SELECT *"
    where_clause = ""
    order_by_clause = ""
    limit_clause = ""

    # Flags to track if age and salary conditions are found
    age_condition_found = False
    salary_condition_found = False

    # Extract components based on POS tagging
    for token in doc:
        if token.pos_ == "NOUN" and token.text.lower() == "employees":
            continue 
        if token.pos_ == "VERB" and token.text.lower() in ("find", "show", "list", "get"):
            continue 
        if token.pos_ == "ADJ" and token.head.pos_ == "NOUN":
            if token.head.text.lower() == "age" and token.text.lower() in ("above", "greater", "more", "older"):
                next_token = doc[token.i + 1]
                where_clause += f"age > {next_token.text} "
                age_condition_found = True
            elif token.head.text.lower() == "salary" and token.text.lower() == "highest":
                order_by_clause = "ORDER BY salary DESC "
                limit_clause = "FETCH FIRST 1 ROWS ONLY"
                salary_condition_found = True
            elif token.head.text.lower() == "salary" and token.text.lower() == "lowest":
                order_by_clause = "ORDER BY salary ASC "
                limit_clause = "FETCH FIRST 1 ROWS ONLY"
                salary_condition_found = True

    # Construct the final SQL query
    sql_query = f"{select_clause} FROM {table_name} "
    if where_clause:
        sql_query += "WHERE " + where_clause
    if order_by_clause:
        sql_query += order_by_clause
    if limit_clause:
        sql_query += limit_clause

    return sql_query.strip()

# Sample sentences
sentences = [
    "Find employees aged above 30 with the highest salary.",
    "Show me the employees who are older than 25.",
    "List the employees with the lowest salary.",
    "Get the details of employees with a salary above 50000."
]

def execute_sql(df, sql_query):
    # This is a simplistic SQL executor for pandas DataFrame
    # It supports only SELECT * and simple WHERE clauses for this example
    if "WHERE" in sql_query:
        query = sql_query.split("WHERE")[1].strip().split(" ")[0] + " " + sql_query.split("WHERE")[1].strip().split(" ")[1] + " " + sql_query.split("WHERE")[1].strip().split(" ")[2]
        result = df.query(query)
    else:
        result = df

    if "ORDER BY" in sql_query:
        order_by_clause = sql_query.split("ORDER BY")[1].strip().split()[0]
        ascending = "ASC" in sql_query
        result = result.sort_values(by=order_by_clause, ascending=ascending)

    if "FETCH FIRST" in sql_query:
        limit = int(sql_query.split("FETCH FIRST")[1].strip().split()[0])
        result = result.head(limit)

    return result

# Execute the generated SQL commands
for sentence in sentences:
    sql_command = sentence_to_sql_with_pos(sentence)
    print("Generated SQL command:")
    print(sql_command)
    result = execute_sql(df, sql_command)
    print("Result:")
    print(result)
    print("\n")

Generated SQL command:
SELECT * FROM Employees ORDER BY salary DESC FETCH FIRST 1 ROWS ONLY
Result:
   id_no first_name last_name  age   salary
3    104      Bulai   Chandra   45  80000.0


Generated SQL command:
SELECT * FROM Employees
Result:
   id_no first_name  last_name  age   salary
0    101      Anata     Sarkar   28  55000.0
1    102    Asutosh  Mukherjee   34  63000.0
2    103       Rada   Sengupto   25  45000.0
3    104      Bulai    Chandra   45  80000.0
4    105   Chaitali  Mukherjee   30  57000.0


Generated SQL command:
SELECT * FROM Employees ORDER BY salary ASC FETCH FIRST 1 ROWS ONLY
Result:
   id_no first_name last_name  age   salary
2    103       Rada  Sengupto   25  45000.0


Generated SQL command:
SELECT * FROM Employees
Result:
   id_no first_name  last_name  age   salary
0    101      Anata     Sarkar   28  55000.0
1    102    Asutosh  Mukherjee   34  63000.0
2    103       Rada   Sengupto   25  45000.0
3    104      Bulai    Chandra   45  80000.0
4    105   Chaitali  Mukherjee   30  57000.0

In [1]:
import spacy
import pandas as pd

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Example dataset
data = {
    "id_no": [101, 102, 103, 104, 105],
    "first_name": ["Anata", "Asutosh", "Rada", "Bulai", "Chaitali"],
    "last_name": ["Sarkar", "Mukherjee", "Sengupto", "Chandra", "Mukherjee"],
    "age": [28, 34, 25, 45, 30],
    "salary": [55000.00, 63000.00, 45000.00, 80000.00, 57000.00]
}

df = pd.DataFrame(data)

# Function to convert a sentence to SQL command using POS tagging
def sentence_to_sql_with_pos(sentence):
    doc = nlp(sentence)

    # Initialize variables for constructing the SQL query
    table_name = "Employees"
    select_clause = "SELECT *"
    where_clause = ""
    order_by_clause = ""
    limit_clause = ""

    # Flags to track if age and salary conditions are found
    age_condition_found = False
    salary_condition_found = False

    # Extract components based on POS tagging
    for token in doc:
        if token.pos_ == "NOUN" and token.text.lower() == "employees":
            continue  # Skip reference to table name
        if token.pos_ == "VERB" and token.text.lower() in ("find", "show", "list", "get","Tell"):
            continue  # Skip verbs not relevant to SQL construction
        if token.pos_ == "ADJ" and token.head.pos_ == "NOUN":
            if token.head.text.lower() == "age" and token.text.lower() in ("above", "greater", "more", "older"):
                next_token = doc[token.i + 1]
                where_clause += f"age > {next_token.text} "
                age_condition_found = True
            elif token.head.text.lower() == "age" and token.text.lower() in ("bellow","younger","smaller","less"):
                next_token = doc[token.i + 1]
                where_clause += f"age < {next_token.text} "
                age_condition_found = True
            elif token.head.text.lower() == "salary" and token.text.lower() == "highest":
                order_by_clause = "ORDER BY salary ASC "
                limit_clause = "FETCH FIRST 1 ROWS ONLY"
                salary_condition_found = True
             elif token.head.text.lower() == "salary" and token.text.lower() == "lowest":
                order_by_clause = "ORDER BY salary DESC "
                limit_clause = "FETCH FIRST 1 ROWS ONLY"
                salary_condition_found = True
            elif token.head.text.lower() == "salary" and token.text.lower() == "lowest":
                order_by_clause = "ORDER BY salary ASC "
                limit_clause = "FETCH FIRST 1 ROWS ONLY"
                salary_condition_found = True

    # Construct the final SQL query
    sql_query = f"{select_clause} FROM {table_name} "
    if where_clause:
        sql_query += "WHERE " + where_clause
    if order_by_clause:
        sql_query += order_by_clause
    if limit_clause:
        sql_query += limit_clause

    return sql_query.strip()

def execute_sql(df, sql_query):
    # This is a simplistic SQL executor for pandas DataFrame
    # It supports only SELECT * and simple WHERE clauses for this example
    if "WHERE" in sql_query:
        query = sql_query.split("WHERE")[1].strip().split(" ")[0] + " " + sql_query.split("WHERE")[1].strip().split(" ")[1] + " " + sql_query.split("WHERE")[1].strip().split(" ")[2]
        result = df.query(query)
    else:
        result = df

    if "ORDER BY" in sql_query:
        order_by_clause = sql_query.split("ORDER BY")[1].strip().split()[0]
        ascending = "ASC" in sql_query
        result = result.sort_values(by=order_by_clause, ascending=ascending)

    if "FETCH FIRST" in sql_query:
        limit = int(sql_query.split("FETCH FIRST")[1].strip().split()[0])
        result = result.head(limit)

    return result
    

# Interactive loop
print("Enter your queries in natural language (type 'exit' to stop):")
while True:
    sentence = input("Query: ")
    if sentence.lower() == 'exit':
        break
    sql_command = sentence_to_sql_with_pos(sentence)
    print("Generated SQL command:")
    print(sql_command)
    result = execute_sql(df, sql_command)
    print("Result:")
    print(result)
    print("\n")

Enter your queries in natural language (type 'exit' to stop):

Query:  list me employees with age below 30 and salary above 50000

Generated SQL command:
SELECT * FROM Employees
Result:
   id_no first_name  last_name  age   salary
0    101      Anata     Sarkar   28  55000.0
1    102    Asutosh  Mukherjee   34  63000.0
2    103       Rada   Sengupto   25  45000.0
3    104      Bulai    Chandra   45  80000.0
4    105   Chaitali  Mukherjee   30  57000.0

KeyboardInterrupt: Interrupted by user

In [ ]:
import spacy
import pandas as pd

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Example dataset
data = {
    "id_no": [101, 102, 103, 104, 105],
    "first_name": ["Anata", "Asutosh", "Rada", "Bulai", "Chaitali"],
    "last_name": ["Sarkar", "Mukherjee", "Sengupto", "Chandra", "Mukherjee"],
    "age": [28, 34, 25, 45, 30],
    "salary": [55000.00, 63000.00, 45000.00, 80000.00, 57000.00]
}

df = pd.DataFrame(data)

# Function to convert a sentence to SQL command using POS tagging
def sentence_to_sql_with_pos(sentence):
    doc = nlp(sentence)

    # Initialize variables for constructing the SQL query
    table_name = "Employees"
    select_clause = "SELECT *"
    where_clause = ""
    order_by_clause = ""
    limit_clause = ""

    # Flags to track if age and salary conditions are found
    age_condition_found = False
    salary_condition_found = False

    # Extract components based on POS tagging
    for token in doc:
        if token.pos_ == "NOUN" and token.text.lower() == "employees":
            continue  # Skip reference to table name
        if token.pos_ == "VERB" and token.text.lower() in ("find", "show", "list", "get", "tell"):
            continue  # Skip verbs not relevant to SQL construction
        if token.pos_ == "ADJ" and token.head.pos_ == "NOUN":
            if token.head.text.lower() == "age" and token.text.lower() in ("above", "greater", "more", "older"):
                next_token = doc[token.i + 1]
                where_clause += f"age > {next_token.text} "
                age_condition_found = True
            elif token.head.text.lower() == "age" and token.text.lower() in ("below", "younger", "smaller", "less"):
                next_token = doc[token.i + 1]
                where_clause += f"age < {next_token.text} "
                age_condition_found = True
            elif token.head.text.lower() == "salary" and token.text.lower() == "highest":
                order_by_clause = "ORDER BY salary ASC "
                limit_clause = "FETCH FIRST 1 ROWS ONLY"
                salary_condition_found = True
            elif token.head.text.lower() == "salary" and token.text.lower() == "lowest":
                order_by_clause = "ORDER BY salary DESC "
                limit_clause = "FETCH FIRST 1 ROWS ONLY"
                salary_condition_found = True

    # Construct the final SQL query
    sql_query = f"{select_clause} FROM {table_name} "
    if where_clause:
        sql_query += "WHERE " + where_clause
    if order_by_clause:
        sql_query += order_by_clause
    if limit_clause:
        sql_query += limit_clause

    return sql_query.strip()

# Function to execute SQL query on pandas DataFrame
def execute_sql(df, sql_query):
    # This is a simplistic SQL executor for pandas DataFrame
    # It supports only SELECT * and simple WHERE clauses for this example
    result = df.copy()  # Create a copy of the DataFrame to avoid modifying the original
    
    if "WHERE" in sql_query:
        where_clause = sql_query.split("WHERE")[1].strip()
        result = result.query(where_clause)

    if "ORDER BY" in sql_query:
        order_by_clause = sql_query.split("ORDER BY")[1].strip().split()[0]
        ascending = "ASC" in sql_query.upper()
        result = result.sort_values(by=order_by_clause, ascending=ascending)

    if "FETCH FIRST" in sql_query:
        limit = int(sql_query.split("FETCH FIRST")[1].strip().split()[0])
        result = result.head(limit)

    return result

# Interactive loop
print("Enter your queries in natural language (type 'exit' to stop):")
while True:
    sentence = input("Query: ")
    if sentence.lower() == 'exit':
        break
    sql_command = sentence_to_sql_with_pos(sentence)
    print("Generated SQL command:")
    print(sql_command)
    result = execute_sql(df, sql_command)
    print("Result:")
    print(result)
    print("\n")

Enter your queries in natural language (type 'exit' to stop):

Query:  show me the employee age below 30 with highest salary

Generated SQL command:
SELECT * FROM Employees ORDER BY salary ASC FETCH FIRST 1 ROWS ONLY
Result:
   id_no first_name last_name  age   salary
2    103       Rada  Sengupto   25  45000.0

Query:  show me employee age below 40

Generated SQL command:
SELECT * FROM Employees
Result:
   id_no first_name  last_name  age   salary
0    101      Anata     Sarkar   28  55000.0
1    102    Asutosh  Mukherjee   34  63000.0
2    103       Rada   Sengupto   25  45000.0
3    104      Bulai    Chandra   45  80000.0
4    105   Chaitali  Mukherjee   30  57000.0

Query:  show me the employee age above 25 with highest salary

Generated SQL command:
SELECT * FROM Employees ORDER BY salary ASC FETCH FIRST 1 ROWS ONLY
Result:
   id_no first_name last_name  age   salary
2    103       Rada  Sengupto   25  45000.0

Query:  show me the employee age above 25

Generated SQL command:
SELECT * FROM Employees
Result:
   id_no first_name  last_name  age   salary
0    101      Anata     Sarkar   28  55000.0
1    102    Asutosh  Mukherjee   34  63000.0
2    103       Rada   Sengupto   25  45000.0
3    104      Bulai    Chandra   45  80000.0
4    105   Chaitali  Mukherjee   30  57000.0

Query:  show me the employee age above 40

Generated SQL command:
SELECT * FROM Employees
Result:
   id_no first_name  last_name  age   salary
0    101      Anata     Sarkar   28  55000.0
1    102    Asutosh  Mukherjee   34  63000.0
2    103       Rada   Sengupto   25  45000.0
3    104      Bulai    Chandra   45  80000.0
4    105   Chaitali  Mukherjee   30  57000.0

Query:  List the employees with the lowest salary.

Generated SQL command:
SELECT * FROM Employees ORDER BY salary DESC FETCH FIRST 1 ROWS ONLY
Result:
   id_no first_name last_name  age   salary
3    104      Bulai   Chandra   45  80000.0